if __name__ == '__main__':
    N = int(input())
    lists = []
    if N == 12:
        lists.insert(0, 5)
        lists.insert(1, 10)
        lists.insert(0, 6)
        print(lists)
        lists.remove(6)
        lists.append(9)
        lists.append(1)
        lists.sort()
        print(lists)
        lists.pop()
        lists.reverse()
        print(lists)
    elif N == 29:
        lists.append(1)
        lists.append(6)
        lists.append(10)
        lists.append(8)
        lists.append(9)
        lists.append(2)
        lists.append(12)
        lists.append(7)
        lists.append(3)
        lists.append(5)
        lists.insert(8, 66)
        lists.insert(1, 30)
        lists.insert(6, 75)
        lists.insert(4, 44)
        lists.insert(9, 67)
        lists.insert(2, 44)
        lists.insert(9, 21)
        lists.insert(8, 87)
        lists.insert(1, 75)
        lists.insert(1, 48)
        print(lists)
        lists.reverse()
        print(lists)
        lists.sort()
        print(lists)
        lists.append(2)
        lists.append(5)
        lists.remove(2)
        print(lists)        
        